variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

image: maven:3-eclipse-temurin-17-alpine #latest

cache:
  paths:
    - .m2/repository/

test:
  script: mvn test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml
